twig:
    file_name_pattern: '*.twig'
    globals:
        cart_service: '@App\Service\CartService'
        categorie_repository: '@App\Repository\CategorieRepository'
        google_maps_key: '%env(MAPS_KEY)%'

when@test:
    twig:
        strict_variables: true
