twig:
    file_name_pattern: '*.twig'
    globals:
        cart_service: '@App\Service\CartService'
        categorie_repository: '@App\Repository\CategorieRepository'

when@test:
    twig:
        strict_variables: true
